### ISSUE TITLE
Automated export and aggregation of results 

### ISSUE THREAD

**Issue by trouille** [zooniverse/intro2astro-server#2]
Ability for an intro2astro instructor to click a button to initiate the export and aggregation of the results (maybe using caesar?) from a group of students in a given intro2astro course working on the following projects:

- https://www.zooniverse.org/projects/trouille/intro2astro-intro-to-data-analysis
- zooniverse.org/projects/srallen/galaxy-zoo-in-astronomy-101
- zooniverse.org/projects/srallen/intro2astro-hubbles-law

**Comment by trouille** [comment]
The plan is to have two buttons:

1) Click here to generate the aggregated result. 
2) Click here to send your raw and aggregated results to your classroom's Google sheet. See https://github.com/zooniverse/intro2astro-server/issues/3

**Comment by srallen** [comment]
This may mean adding classification export by user group. This would require thinking about how to implement with changes on how the export permissions work. Two ways:

- Initiate export by the zooniverse user in admin mode (potentially dangerous)
- Initiate export by user with "educator" role on Education API that the gets a proxy role as a collaborator on the Panoptes project. 

Export for activities aren't going to be raw classification exports, but will be aggregated, so possibly will be handled by caesar rather than a direct request to the Panoptes export endpoint.

**Comment by srallen** [comment]
Sending to a google sheet needs to be optional since not all institutions use Google apps for Education, so an option needs to be available to get the aggregated CSV independently.

**Comment by srallen** [comment]
Closing in favor of zooniverse/rfc#23
